---
    name: Submodule Updates
    
    #############################
    # Start the job on all push #
    #############################
    on:
      push:
        branches-ignore: [master, main, ci_development]
      pull_request:
        branches: [master, main]
    
    ###############
    # Set the Job #
    ###############
    jobs:
      build:
        name: Submodule update
        runs-on: ubuntu-latest
        env:
          PARENT_REPOSITORY: 'labjack/ljsimpleregisterlookup'
          CHECKOUT_BRANCH: 'main'
          PR_AGAINST_BRANCH: 'main'
          OWNER: 'labjack'
    
        steps:
          ##########################
          # Checkout the code base #
          ##########################
          - name: Checkout Code
            uses: actions/checkout@v2
    
          ####################################
          # Run the action against code base #
          ####################################
          - name: run action
            id: run_action
            uses: releasehub-com/github-action-create-pr-parent-submodule@v1
            with:
              github_token: ${{ secrets.ACCESS_TOKEN }}
              parent_repository: ${{ env.PARENT_REPOSITORY }}
              checkout_branch: ${{ env.CHECKOUT_BRANCH}}
              pr_against_branch: ${{ env.PR_AGAINST_BRANCH }}
              owner: ${{ env.OWNER }}